name = "zhost-photo-bot"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "BOT_SESSIONS"
id = "c928cb81c43a44d2b52faa3e820e2960"