name = "zhost-photo-bot"
main = "src/index.ts"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "BOT_SESSIONS"
id = "0b52f9902754444e9239a6e10ad923f5"